#- name: Demo on Ansible variables
##  hosts: all
##  vars:
##    URL: example.com
##  tasks:
##    - name: Print URL
##      ansible.builtin.debug:
##        msg: URL - {{ URL }}

- name: Demo on Register Keyword
  hosts: localhost
  connection: local
  tasks:
    - name: Store uptime via Register variable
      ansible.builtin.shell: uptime
      register: output

    - name: Print Output
      ansible.builtin.debug:
        msg: "{{ output.end }}"