- name: Demo on Loops
  hosts: local host
  connection: local
  tasks:
    - name: Printing fruit names in a loop
      ansible.builtin.debug:
        msg: Fruit Name = {{ item }}
      loop:
        - mango
        - apple
        - banana
        - orange

    - name: Printing fruit name and quantity
      ansible.builtin.debug:
        msg: Fruit name - {{ item.name }}, Quantity - {{ item.quantity }}
      loop:
        - {name: mango, quantity: 100}
        - {name: apple, quantity: 200}
        - {name: banana, quantity: 300}
        - {name: orange, quantity: 500}