- name: Fetch aws ssm parameter
  hosts: localhost
  connection: local
  tasks:
   - name: Fetch and print aws ssm parameter
     ansible.builtin.debug:
      msg: parameter is {{ lookup('amazon.aws.aws_ssm', 'test.test', region='us-east-1') }}

